- hosts: all
  gather_facts: false

  tasks:
    - name: Create single ec2 key pair
      amazon.aws.ec2_key:
        region: "{{ aws_region | default('us-east-1') }}"
        state: "{{ key_state | default(omit) }}"
        key_type: ed25519
        name: "{{ key_name }}"
