- hosts: all
  gather_facts: false

  environment:
    AWS_REGION: us-east-1

  roles:
    - role: cloud.terraform_ops.aws_s3backend
      aws_s3backend_operation: "{{ operation | default('create') }}"
      aws_s3backend_bucket_name: "{{ bucket_name }}"
      aws_s3backend_dynamodb_table_name: "{{ db_table_name }}"
      aws_s3backend_iam_name: "{{ iam_name }}"
      aws_s3backend_delete_iam_resource: true
      aws_s3backend_iam_type: role
      aws_s3backend_terraform_state_path: '.terraform/state'
