---
- name: awx terraform credentials for s3 backend with dynamoDB for state lock
  hosts: all
  gather_facts: false

  tasks:
    - name: create temporary file for terraform configuration
      ansible.builtin.tempfile:
        state: directory
      register: tmpdir

    - name: Run terraform configuration
      block:
        - name: Download terraform configuration file
          ansible.builtin.get_url:
            url: "{{ tf_config_url }}"
            dest: "{{ tmpdir.path }}/main.tf"

        - name: Reading TF BE config secret
          ansible.builtin.set_fact:
            tf_backend_config_file: "{{ lookup('env', 'TF_BACKEND_CONFIG_FILE') }}"

        - name: Create/Delete simple terraform project
          cloud.terraform.terraform:
            force_init: true
            state: "{{ tf_state | default(omit) }}"
            project_path: '{{ tmpdir.path }}'
            backend_config_files: 
              - "{{ tf_backend_config_file }}"
            variables: "{{ tf_vars | default(omit) }}"

        - name: Read terraform output
          cloud.terraform.terraform_output:
            project_path: "{{ tmpdir.path }}"
          register: tf_out

        - name: Display terraform output
          ansible.builtin.debug:
            var: tf_out

      always:
        - name: Delete temporary file
          ansible.builtin.file:
            state: absent
            path: "{{ tmpdir.path }}"
