- hosts: all
  gather_facts: false

  roles:
    - role: cloud.terraform_ops.aws_s3backend
      aws_s3backend_operation: "{{ operation | default('create') }}"
      aws_s3backend_bucket_name: "{{ bucket_name }}"
      aws_s3backend_dynamodb_table_name: "{{ db_table_name }}"

    - role: cloud.terraform_ops.gcs_backend
      gcs_backend_operation: "{{ operation | default('create') }}"
      gcs_backend_bucket_name: "{{ bucket_name }}"

    # - role: cloud.terraform_ops.azurerm_backend
    #   azurerm_backend_operation: "{{ operation | default('create') }}"
    #   azurerm_backend_resource_group_name: "{{ resource_group }}"
    #   azurerm_backend_location: "{{ resource_group_location }}"
    #   azurerm_backend_container_name: "terraform_state"