---
- name: Terraform Backend configuration
  hosts: localhost
  gather_facts: false

  tasks:
    - name: create temporary file for terraform configuration
      ansible.builtin.tempfile:
        state: directory
      register: tmpdir

    - name: Run terraform configuration
      block:
        - name: Download terraform configuration template
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/abikouo/aws_playbook/main/terraform/templates/ansible_provider.tf.j2
            dest: "{{ tmpdir.path }}/main.tf"

        - name: create simple terraform project
          cloud.terraform.terraform:
            force_init: true
            state: present
            project_path: '{{ tmpdir.path }}'
            backend_config_files: "{{ lookup('env', 'TF_BACKEND_CONFIG_FILE') }}"
            variables:
              host_name: "tf_backend_config_file"
              host_ip: localhost
              host_user: ansible

      always:
        - name: Delete temporary file
          ansible.builtin.file:
            state: absent
            path: "{{ tmpdir.path }}"
